name: AccuKnox Container Scan Action

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  accuknox-cicd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main  
   
      - name: Run AccuKnox Container Scan Action
        uses: 'accuknox/container-scan-action@v0.0.1'
        with:
          token: ${{ secrets.TOKEN }}
          tenant_id: ${{ secrets.TENANT_ID }}
          repository_name: "accuknox/client-cli"
          severity: "CRITICAL"
